### ISSUE TITLE
Inconsistency between Regular Expressions using \d and [0-9] in Egrep

### ISSUE THREAD

**Issue by R3ye5** [pengzhile/cocopilot#12]
## Problem

Running the following `grep -E` command with the regular expression `^github\.copilot-\d+\.\d+\.\d+$` doesn't return any results: 
```
ls -lt /root/.vscode-server/extensions | grep '^d' | awk '{print $9}'|grep -E ^github\.copilot-\d+\.\d+\.\d+$
```
However, when we replace `\d` with `[0-9]`, it returns the expected results: 
```
ls -lt /root/.vscode-server/extensions | grep '^d' | awk '{print $9}'|grep -E '^github.copilot-[0-9]+\.[0-9]+\.[0-9]+$'
```
The output is: `github.copilot-1.108.376`

The `\d` should match any digit and is often more readable than [0-9], but these two commands produce different results.

## Expected Behavior

Both commands should return the same results, as both regular expressions are supposed to match exactly the same patterns.

## Actual Behavior

The command using `\d` returns no results, while replacing `\d` with `[0-9]` returns the expected output.

## Steps to Reproduce

1. Run `ls -lt /root/.vscode-server/extensions | grep '^d' | awk '{print $9}'|grep -E ^github\.copilot-\d+\.\d+\.\d+$`
2. Observe no output.
3. Run `ls -lt /root/.vscode-server/extensions | grep '^d' | awk '{print $9}'|grep -E '^github.copilot-[0-9]+\.[0-9]+\.[0-9]+$'`
4. Observe the correct output: `github.copilot-1.108.376`

We need a fix or an explanation for this

-- openai

**Comment by leowyzhang** [comment]
Regular expressions have many different engines. They all support [0-9],  Not all support  \d.
if you use Linux, you can use  'grep -P'  to replace 'grep -E'.
if you use MacOS , -P is invalid .
-P means Perl RegEx
-E means Extended RegEx

**Comment by pengzhile** [comment]
fixed
