### ISSUE TITLE
不是VSCode 不更新了，是Visual Studio for Mac 不更新了

### ISSUE THREAD

**Issue by wangyingbo** [pengzhile/cocopilot#2]
如题，微软宣布不更新的是 Visual Studio for Mac，不是VSCode。

贴一条新闻链接：[https://www.zhihu.com/question/619961779](https://www.zhihu.com/question/619961779)

**Comment by shunichio** [comment]
同求支持 VSCode，前端开发很需要，WebStorm太重了。

**Comment by cnx7** [comment]
附议，VS 非 VSCode

**Comment by pengzhile** [comment]
已支持。
