### ISSUE TITLE
copilot 没有工作

### ISSUE THREAD

**Issue by lingfengchencn** [pengzhile/cocopilot#21]
vs code已经安装copilot
code.sh 安装成功 提示
```
done. please restart your vscode.
```
可是没有提示，是因为github copilot 过期了么？

**Comment by pengzhile** [comment]
重启IDE，看右下角是不是已经登录状态。

**Comment by lingfengchencn** [comment]
再左下角人头那边退出了github 
![image](https://github.com/pengzhile/cocopilot/assets/2757011/ba580b52-9ce6-4ef2-b490-6f0b5faec350)

重启了vs code。
左下脚人头像显示“未登录任何账户“，
copilot状态：
![image](https://github.com/pengzhile/cocopilot/assets/2757011/98260794-32b1-44cf-ba63-7b0e7892f49b)

**Comment by pengzhile** [comment]
左下角不用管。你这copilot看起来正常的。

**Comment by lingfengchencn** [comment]
但是不工作。。。
![QQ20230907-103417-HD](https://github.com/pengzhile/cocopilot/assets/2757011/13054131-3931-472f-adae-06b438f1ec18)

**Comment by pengzhile** [comment]
copilot可能有墙。

![image](https://github.com/pengzhile/cocopilot/assets/343491/a8d5c816-8d05-4bd9-8749-ec4ecc775f7e)

**Comment by lingfengchencn** [comment]
梯子是挂着的，看起来是没有生效。用不了啦？

**Comment by pengzhile** [comment]
你看我的截图不是好的吗

**Comment by lingfengchencn** [comment]
那看来用不了咯
