### ISSUE TITLE
实测有效

### ISSUE THREAD

**Issue by mikoForDream** [pengzhile/cocopilot#22]
稳定不稳定，另说，确实可以激活

**Comment by fzfz666** [comment]
老哥，请问这个需要用自己的key吗

**Comment by mikoForDream** [comment]
> 老哥，请问这个需要用自己的key吗

不需要，直接按照首页RM文件操作就行，无脑简单

**Comment by fzfz666** [comment]
好滴，谢谢老哥

**Comment by Hellotzt** [comment]
<img width="444" alt="image" src="https://github.com/pengzhile/cocopilot/assets/76930592/a2b2ad71-7c79-484f-b27e-4ae857b436ae">
为啥我显示了这个，执行sh文件后登录态就掉了

**Comment by pengzhile** [comment]
网络问题

> <img alt="image" width="444" src="https://user-images.githubusercontent.com/76930592/266193837-a2b2ad71-7c79-484f-b27e-4ae857b436ae.png"> 为啥我显示了这个，执行sh文件后登录态就掉了

**Comment by mikoForDream** [comment]
> 网络问题
> 
> > <img alt="image" width="444" src="https://user-images.githubusercontent.com/76930592/266193837-a2b2ad71-7c79-484f-b27e-4ae857b436ae.png"> 为啥我显示了这个，执行sh文件后登录态就掉了

不应该执行.bat文件么
