### ISSUE TITLE
不知道为什么一直是ECONNRESET

### ISSUE THREAD

**Issue by rainerosion** [pengzhile/cocopilot#32]
不知道为什么在idea安装了插件以后运行bat重启idea一只都是这样`Sign in failed. Reason: Request signInInitiate failed with message: read ECONNRESET, request id: 33, error code: -32603`。头疼
![image](https://github.com/pengzhile/cocopilot/assets/11945383/20067948-9464-40d5-9352-a2253d3a91fe)
尝试了
- PROXY软件直接开全局-失败

- IDEA里面PROXY设置http和socks-失败

- IDEA关闭PROXY-失败

![image](https://github.com/pengzhile/cocopilot/assets/11945383/75ce9554-eb2a-4ccf-bfd3-a89928c4fab9)

![image](https://github.com/pengzhile/cocopilot/assets/11945383/f610b15f-24ab-400b-ba45-3bdc5be9b8c6)

**Comment by zhaomy0506** [comment]
使用tun模式
