### ISSUE TITLE
怎么卸载

### ISSUE THREAD

**Issue by maple-dawn** [pengzhile/cocopilot#41]
不想用了，我登录了自己的GitHub账号，但是copilot还是提示我登录的其他账号

**Comment by pengzhile** [comment]
应该是vscode吧，重装copilot插件即可。

**Comment by mchades** [comment]
你好，请问下JetBrains的不想用了，要怎么卸载？ @pengzhile

**Comment by pengzhile** [comment]
> 你好，请问下JetBrains的不想用了，要怎么卸载？ @pengzhile

退出登录即可。
