### ISSUE TITLE
后台账号似乎是窃取的他人项目的

### ISSUE THREAD

**Issue by wyelims1** [pengzhile/cocopilot#42]
从别人的报错信息中可以看到该项目使用的账号基本都源于窃取他人项目的账号，还请尽快将这部分账号删除

**Comment by pengzhile** [comment]
你哪位？号在闲鱼买的，有什么问题？

**Comment by wyelims1** [comment]
如果您是购买的账号，那您理应能够登录该账号并star其他项目，对于issue #40 中出现的账号，您可以用该账号star一下该仓库以证明账号所有权是您

**Comment by pengzhile** [comment]
> 如果您是购买的账号，那您理应能够登录该账号并star其他项目，对于issue #40 中出现的账号，您可以用该账号star一下该仓库以证明账号所有权是您

现在闲鱼买copilot不给账号的你不知道吗？只是给下发token，买的都是token。

**Comment by wyelims1** [comment]
但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号

**Comment by pengzhile** [comment]
> 但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号

是吗，那您star一下看看呢。我们从未接触，不可能有您的账号信息，我的token确实是来自闲鱼。另外我建议您修改自己的账号信息，别再被号商拿去了。

**Comment by pengzhile** [comment]
如果您就是那个号商，我认为我就有权使用这个token，因为这是购买的商品。

**Comment by wyelims1** [comment]
> > 但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号
> 
> 是吗，那您star一下看看呢。我们从未接触，不可能有您的账号信息，我的token确实是来自闲鱼。另外我建议您修改自己的账号信息，别再被号商拿去了。

star了

**Comment by pengzhile** [comment]
> > > 但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号
> > 
> > 
> > 是吗，那您star一下看看呢。我们从未接触，不可能有您的账号信息，我的token确实是来自闲鱼。另外我建议您修改自己的账号信息，别再被号商拿去了。
> 
> star了

抱歉给您带来的困扰，已经移除。但我并没有窃取您的token，因为如上所说，我不掌握您的账号信息，无从窃取。请保护好您的账号。

**Comment by pipijun998** [comment]
怎么用自己买的token登录呀？我在闲鱼上也买了几个token，但是都绑定了机器码。

**Comment by pengzhile** [comment]
> > > 但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号
> > 
> > 
> > 是吗，那您star一下看看呢。我们从未接触，不可能有您的账号信息，我的token确实是来自闲鱼。另外我建议您修改自己的账号信息，别再被号商拿去了。
> 
> star了

![5b58188eedff42d7693d80f39cbaddca](https://github.com/pengzhile/cocopilot/assets/343491/ac64ce22-9bd2-4990-bca6-7f44eb3cab9e)

破案了，号商才是盗号的。

**Comment by wyelims1** [comment]
> > > > 但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号
> > > 
> > > 
> > > 是吗，那您star一下看看呢。我们从未接触，不可能有您的账号信息，我的token确实是来自闲鱼。另外我建议您修改自己的账号信息，别再被号商拿去了。
> > 
> > 
> > star了
> 
> 抱歉给您带来的困扰，已经移除。但我并没有窃取您的token，因为如上所说，我不掌握您的账号信息，无从窃取。请保护好您的账号。
不 淘宝和闲鱼的token就是我给他们的，他们本质上是卖共享账号，也就是说固定的多少人共用一个账号，你可以看到你从他们的系统里扣出来的大部分token都是付费账号而不是免费学生包账号，而你的行为直接导致了每个号的使用人数激增。个人认为你找方法去薅资本主义羊毛我不管，但是你直接薅闲鱼淘宝卖家的共享号是不是有些过分了。人家不是72一个月原价卖你的，人家是按照共享账号的加个卖你的。

**Comment by pengzhile** [comment]
> > > > 但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号
> > > 
> > > 
> > > 是吗，那您star一下看看呢。我们从未接触，不可能有您的账号信息，我的token确实是来自闲鱼。另外我建议您修改自己的账号信息，别再被号商拿去了。
> > 
> > 
> > star了
> 
> 抱歉给您带来的困扰，已经移除。但我并没有窃取您的token，因为如上所说，我不掌握您的账号信息，无从窃取。请保护好您的账号。 不 淘宝和闲鱼的token就是我给他们的，他们本质上是卖共享账号，也就是说固定的多少人共用一个账号，你可以看到你从他们的系统里扣出来的大部分token都是付费账号而不是免费学生包账号，而你的行为直接导致了每个号的使用人数激增。个人认为你找方法去薅资本主义羊毛我不管，但是你直接薅闲鱼淘宝卖家的共享号是不是有些过分了。人家不是72一个月原价卖你的，人家是按照共享账号的加个卖你的。

过分？什么叫过分？我号也是从闲鱼花钱买来的，你跑过来教我如何使用我购买的账号吗？？？

**Comment by wyelims1** [comment]
> > > > > 但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号
> > > > 
> > > > 
> > > > 是吗，那您star一下看看呢。我们从未接触，不可能有您的账号信息，我的token确实是来自闲鱼。另外我建议您修改自己的账号信息，别再被号商拿去了。
> > > 
> > > 
> > > star了
> > 
> > 
> > 抱歉给您带来的困扰，已经移除。但我并没有窃取您的token，因为如上所说，我不掌握您的账号信息，无从窃取。请保护好您的账号。 不 淘宝和闲鱼的token就是我给他们的，他们本质上是卖共享账号，也就是说固定的多少人共用一个账号，你可以看到你从他们的系统里扣出来的大部分token都是付费账号而不是免费学生包账号，而你的行为直接导致了每个号的使用人数激增。个人认为你找方法去薅资本主义羊毛我不管，但是你直接薅闲鱼淘宝卖家的共享号是不是有些过分了。人家不是72一个月原价卖你的，人家是按照共享账号的加个卖你的。
> 
> 过分？什么叫过分？我号也是从闲鱼花钱买来的，你跑过来教我如何使用我购买的账号吗？？？

你买的是认证系统，商家已经限制了你只能单设备使用，但你恶意取出系统中的token并共享，你觉得合理吗

**Comment by pengzhile** [comment]
> > > > > > 但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号
> > > > > 
> > > > > 
> > > > > 是吗，那您star一下看看呢。我们从未接触，不可能有您的账号信息，我的token确实是来自闲鱼。另外我建议您修改自己的账号信息，别再被号商拿去了。
> > > > 
> > > > 
> > > > star了
> > > 
> > > 
> > > 抱歉给您带来的困扰，已经移除。但我并没有窃取您的token，因为如上所说，我不掌握您的账号信息，无从窃取。请保护好您的账号。 不 淘宝和闲鱼的token就是我给他们的，他们本质上是卖共享账号，也就是说固定的多少人共用一个账号，你可以看到你从他们的系统里扣出来的大部分token都是付费账号而不是免费学生包账号，而你的行为直接导致了每个号的使用人数激增。个人认为你找方法去薅资本主义羊毛我不管，但是你直接薅闲鱼淘宝卖家的共享号是不是有些过分了。人家不是72一个月原价卖你的，人家是按照共享账号的加个卖你的。
> > 
> > 
> > 过分？什么叫过分？我号也是从闲鱼花钱买来的，你跑过来教我如何使用我购买的账号吗？？？
> 
> 你买的是认证系统，商家已经限制了你只能单设备使用，但你恶意取出系统中的token并共享，你觉得合理吗

既然商家都限制了单台设备使用，那你怎么认为我没被限制到呢？还有，我买的不是认证系统，我买的是能用的copilot授权，你搞搞清楚。

**Comment by GPT5free** [comment]
你是卖号的吗？侵犯你的利益了吗？搞这么多？真闲的蛋疼呀

**Comment by wyelims1** [comment]
> 你是卖号的吗？侵犯你的利益了吗？搞这么多？真闲的蛋疼呀

对啊 我花72块钱开的copilot 他给我共享出来了 我直接不好用了 你说呢

**Comment by GPT5free** [comment]
那你找闲鱼卖家，关这个项目啥事？

>

**Comment by pengzhile** [comment]
> > 你是卖号的吗？侵犯你的利益了吗？搞这么多？真闲的蛋疼呀
> 
> 对啊 我花72块钱开的copilot 他给我共享出来了 我直接不好用了 你说呢

有意思，你自己坐庄，给淘宝闲鱼卖家搞总/分销机制卖号，一号不知道卖了多少份。现在号不能用，跑过来指责掏钱买号的人，你真是急了什么都做得出啊？

**Comment by GPT5free** [comment]
凡事过来咬的，肯定自己屁股不干净，或者利益相关的
一个免费的东西，要啥自行车？

**Comment by pipijun998** [comment]
这人应该是个号贩子，抢他蛋糕了

**Comment by zhangjunjie6b** [comment]
掀桌子，后端给开源出来

**Comment by pipijun998** [comment]
POST /c/s/m/o/atls/u3/auth HTTP/1.1
Host: githubcopilot.top
User-Agent: NICE-AI
Accept-Encoding: gzip, deflate
Accept: */*
Connection: close
Content-Type: application/json;charset=UTF-8
Content-Length: 356

{"data": "p3OMcAImZHY3CxrYMmaRYT0N73T6o3yAo6RwkB65Xyw8bDpwkiuwDNPJUP3chwDkWUs82dPgIGmDyD2CMCl00e2eJBoBOk+m9DzztOEOc8tSQ7kFMTvg9PYQ5HXrTyPLAGylSH/X5sFGI8ArTcceqT7RWMuHS8u6bzCpsbs0u770CQBUAbLYmth/28WsQplzaug1d7Qqf/J3zy5pgjtwro3d4TWqqia2R6GvYOTLovGLjhWWkdfZ16wMhGofs8vlfqvWSlu25Nnc6rHwZK01LUhrbnOO6j7sWeJ5zs4YiUFHQq8+qncH0LYKDYSz+2O9hhgCdtqd3XCYzv1DVieccg=="}
有个认证的包是这样的，这个data该如何解出来呢？

**Comment by pipijun998** [comment]
> > POST /c/s/m/o/atls/u3/auth HTTP/1.1 Host: githubcopilot.top User-Agent: NICE-AI Accept-Encoding: gzip, deflate Accept: _/_ Connection: close Content-Type: application/json;charset=UTF-8 Content-Length: 356
> > {"data": "p3OMcAImZHY3CxrYMmaRYT0N73T6o3yAo6RwkB65Xyw8bDpwkiuwDNPJUP3chwDkWUs82dPgIGmDyD2CMCl00e2eJBoBOk+m9DzztOEOc8tSQ7kFMTvg9PYQ5HXrTyPLAGylSH/X5sFGI8ArTcceqT7RWMuHS8u6bzCpsbs0u770CQBUAbLYmth/28WsQplzaug1d7Qqf/J3zy5pgjtwro3d4TWqqia2R6GvYOTLovGLjhWWkdfZ16wMhGofs8vlfqvWSlu25Nnc6rHwZK01LUhrbnOO6j7sWeJ5zs4YiUFHQq8+qncH0LYKDYSz+2O9hhgCdtqd3XCYzv1DVieccg=="} 有个认证的包是这样的，这个data该如何解出来呢？
> 
> 一眼看是AES，具体要包发过来分析。
已经发送到你的邮箱，请帮忙分析一下，谢谢

**Comment by vafyl** [comment]
> 

狗急了，号贩子，滚出去

**Comment by Kagenui-yozuru** [comment]
> > > > > > 但issue #40 中出现的账户是我的，不管您获取途径是什么，已经造成了我的账号copilot无法使用的情况，还请您删除这部分账号
> > > > > 
> > > > > 
> > > > > 是吗，那您star一下看看呢。我们从未接触，不可能有您的账号信息，我的token确实是来自闲鱼。另外我建议您修改自己的账号信息，别再被号商拿去了。
> > > > 
> > > > 
> > > > star了
> > > 
> > > 
> > > 抱歉给您带来的困扰，已经移除。但我并没有窃取您的token，因为如上所说，我不掌握您的账号信息，无从窃取。请保护好您的账号。 不 淘宝和闲鱼的token就是我给他们的，他们本质上是卖共享账号，也就是说固定的多少人共用一个账号，你可以看到你从他们的系统里扣出来的大部分token都是付费账号而不是免费学生包账号，而你的行为直接导致了每个号的使用人数激增。个人认为你找方法去薅资本主义羊毛我不管，但是你直接薅闲鱼淘宝卖家的共享号是不是有些过分了。人家不是72一个月原价卖你的，人家是按照共享账号的加个卖你的。
> > 
> > 
> > 过分？什么叫过分？我号也是从闲鱼花钱买来的，你跑过来教我如何使用我购买的账号吗？？？
> 
> 你买的是认证系统，商家已经限制了你只能单设备使用，但你恶意取出系统中的token并共享，你觉得合理吗

如果你是正常使用自己的号然后被号商盗走，那请你注意账号安全。
如果你是号商
# 滚出去！

**Comment by BNTang** [comment]
如果你是正常使用自己的号然后被号商盗走，那请你注意账号安全。
如果你是号商

滚出去！
