### ISSUE TITLE
token 池支持

### ISSUE THREAD

**Issue by lly-ke** [pengzhile/cocopilot#6]
脚本里面的这个token很容易挂掉吧, 能弄个网站分享和获取token吗, 和之前pandora那个token池一样

**Comment by pengzhile** [comment]
这就是个token池。

**Comment by qiuwei** [comment]
感觉更安全点的方式，应该把请求forward到一个proxy上，proxy通过一个token池 round robin发请求。这么多token 不同ip使用，感觉很容易封号吧。

**Comment by Kagenui-yozuru** [comment]
> 感觉更安全点的方式，应该把请求forward到一个proxy上，proxy通过一个token池 round robin发请求。单一token 不同ip使用，感觉很容易封号吧。

现在的实现方式大致也是这样吧，请求发到作者的服务器那里，校验过程在服务器进行的

**Comment by pengzhile** [comment]
> > 感觉更安全点的方式，应该把请求forward到一个proxy上，proxy通过一个token池 round robin发请求。单一token 不同ip使用，感觉很容易封号吧。
> 
> 现在的实现方式大致也是这样吧，请求发到作者的服务器那里，校验过程在服务器进行的

他的意思应该是把解析代码的请求也proxy了，做是能做到，但大家对安全性担忧就上来了。没必要了。
