### ISSUE TITLE
VSCode shell script grep target dir error

### ISSUE THREAD

**Issue by GianmariaMazza** [pengzhile/cocopilot#7]
Using Linux scripts, it was found that the corresponding plugin directory could not be found on Ubuntu 20.04.6 LTS

Since I usually use the -P option of the GREP command a lot, I changed the -E in the script to -P and found that the script ran normally

```bash
ls -lt "$EXTENSIONS_DIR" | grep '^d' | awk '{print $9}' | grep -P '^github\.copilot-\d+\.\d+\.\d+$' | head -n 1
```

But as I understand it, non-Perl formatted regular strings should work, so I tried modifying the regular string with -E in order to make it work.

I find blow bash common with -E will work well.

```bash
ls -lt "$EXTENSIONS_DIR" | grep '^d' | awk '{print $9}' | grep -E '^github\.copilot-[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
```

I found some information that we can refer to together: [Link](https://unix.stackexchange.com/questions/414226/difference-between-0-9-digit-and-d)

Allow me to say that I am currently unable to submit a PR for this modification, I am not currently next to a computer where I have a PR submission environment.

Thanks for provide the tools, hard work.

**Comment by pengzhile** [comment]
fixed
